# Resolução dos Exercícios com Pandas

Dataset: dataset_vendas.csv

## Carregar os dados

In [1]:
import pandas as pd

df = pd.read_csv('dataset_desempenho_escolar.csv')
df.head()

    nome  nota  frequencia
0    Ana   9.0          95
1  Bruno   7.5          80
2  Carol   8.0          88
3  Diego   6.5          70
4  Elisa   9.5         100

## 1. Criar um DataFrame maior com base no dataset original

In [2]:
# Concatenando o dataset com ele mesmo para aumentar o tamanho
df_maior = pd.concat([df, df], ignore_index=True)
df_maior.shape
df = pd.DataFrame(df_maior)
df

        nome  nota  frequencia
0        Ana   9.0          95
1      Bruno   7.5          80
2      Carol   8.0          88
3      Diego   6.5          70
4      Elisa   9.5         100
5      Fabio   5.0          60
6   Giovanna   8.2          90
7     Heitor   4.5          45
8       Igor   7.8          82
9      Julia  10.0          98
10       Ana   9.0          95
11     Bruno   7.5          80
12     Carol   8.0          88
13     Diego   6.5          70
14     Elisa   9.5         100
15     Fabio   5.0          60
16  Giovanna   8.2          90
17    Heitor   4.5          45
18      Igor   7.8          82
19     Julia  10.0          98

## 2. Remover valores negativos

In [3]:
# Removendo valores negativos
df_limpo = df_maior[(df_maior.select_dtypes(include=['number']) >= 0).all(axis=1)]
df_limpo.head()

    nome  nota  frequencia
0    Ana   9.0          95
1  Bruno   7.5          80
2  Carol   8.0          88
3  Diego   6.5          70
4  Elisa   9.5         100

## 3. Criar coluna de multiplicação (nota x frequencia)

In [5]:
# Supondo que existam colunas 'Nota' e 'Frequencia'
df_limpo['multiplicacao_calc'] = df_limpo['nota'] * df_limpo['frequencia']
df_limpo.head()

    nome  nota  frequencia         multiplicacao_calc
0    Ana   9.0          95  855.0               855.0
1  Bruno   7.5          80  600.0               600.0
2  Carol   8.0          88  704.0               704.0
3  Diego   6.5          70  455.0               455.0
4  Elisa   9.5         100  950.0               950.0

## 4. 5 notas mais altas

In [8]:
# Agrupando por nota
df_limpo[df_limpo['nota'] == df_limpo['nota'].max()]
df_limpo.sort_values(by='nota', ascending=False).head(5)

     nome  nota  frequencia         multiplicacao_calc
19  Julia  10.0          98  980.0               980.0
9   Julia  10.0          98  980.0               980.0
4   Elisa   9.5         100  950.0               950.0
14  Elisa   9.5         100  950.0               950.0
10    Ana   9.0          95  855.0               855.0

## 5. Média de notas

In [9]:
media_notas = df_limpo['nota'].mean()
media_notas

np.float64(7.6)