# Módulo 2: Manipulação de Dados
Este notebook usa o dataset fornecido (dataset_vendas.csv).

# Pandas na Prática: Aula Completa

## O que é o Pandas?

Pandas é a principal biblioteca de análise de dados em Python.

### Estruturas:
- Series (1D)
- DataFrame (2D)

### Usos:
- Limpeza de dados
- Análise
- Transformação

## Passo 1: Criando o DataFrame

In [2]:
import pandas as pd
import numpy as np

# Criando o dataset diretamente
data = pd.read_csv('dataset_desempenho_escolar.csv')
df = pd.DataFrame(data)
df

       nome  nota  frequencia
0       Ana   9.0          95
1     Bruno   7.5          80
2     Carol   8.0          88
3     Diego   6.5          70
4     Elisa   9.5         100
5     Fabio   5.0          60
6  Giovanna   8.2          90
7    Heitor   4.5          45
8      Igor   7.8          82
9     Julia  10.0          98

## Limpeza de Dados

In [4]:
# Simulando problema de dados
df.loc[1, 'frequencia'] = -22

# Removendo valores negativos
df_clean = df[df['frequencia'] > 0]

df_clean

       nome  nota  frequencia
0       Ana   9.0          95
2     Carol   8.0          88
3     Diego   6.5          70
4     Elisa   9.5         100
5     Fabio   5.0          60
6  Giovanna   8.2          90
7    Heitor   4.5          45
8      Igor   7.8          82
9     Julia  10.0          98

## Transformação de Dados

In [ ]:
# Código original (não executado automaticamente)
# Criando nova coluna
df_clean['divisao_calc'] = df_clean['nota'] / df_clean['frequencia']

df_clean


# Erro ao executar automaticamente: name 'df_clean' is not defined

C:\Users\samue\AppData\Local\Temp\ipykernel_14340\1582939433.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['division_calc'] = df_clean['nota'] / df_clean['frequencia']

       nome  nota  frequencia  division_calc
0       Ana   9.0          95       0.094737
2     Carol   8.0          88       0.090909
3     Diego   6.5          70       0.092857
4     Elisa   9.5         100       0.095000
5     Fabio   5.0          60       0.083333
6  Giovanna   8.2          90       0.091111
7    Heitor   4.5          45       0.100000
8      Igor   7.8          82       0.095122
9     Julia  10.0          98       0.102041

## Estatística Descritiva

In [6]:
# Código original (não executado automaticamente)
# Estatísticas gerais
df_clean.describe()


# Erro ao executar automaticamente: name 'df_clean' is not defined

            nota  frequencia  fequencia  revenue_calc
count   9.000000    9.000000        0.0      9.000000
mean    7.611111   80.888889        NaN    647.122222
std     1.919274   18.824482        NaN    276.676679
min     4.500000   45.000000        NaN    202.500000
25%     6.500000   70.000000        NaN    455.000000
50%     8.000000   88.000000        NaN    704.000000
75%     9.000000   95.000000        NaN    855.000000
max    10.000000  100.000000        NaN    980.000000

In [ ]:
# Código original (não executado automaticamente)
# Média
df_clean['nota'].mean()


# Erro ao executar automaticamente: name 'df_clean' is not defined

np.float64(736.4042553191489)

In [ ]:
# Código original (não executado automaticamente)
# Mediana
df_clean['nota'].median()


# Erro ao executar automaticamente: name 'df_clean' is not defined

np.float64(218.5)

In [ ]:
# Código original (não executado automaticamente)
# Desvio padrão
df_clean['nota'].std()


# Erro ao executar automaticamente: name 'df_clean' is not defined

np.float64(973.9338402288874)

## Exercícios Finais

1. Crie um DataFrame maior com base no dataset original.
2. Remova valores negativos.
3. Crie uma coluna de multiplicação.
4. Descubra as 5 notas mais altas.
5. Descubra a média de notas.